title: Criação de um Jogo 2D com o GameMaker
description: Elaborado por Paulo Cesar Nicolau Padilha, do quinto período de Bacharelado em Sistemas de Informação - Instituto Federal Catarinense Campus Araquari
remote-theme: qwtel/jekyll-theme-hydejack
