global.btn_cima = keyboard_check(ord("W"))
global.btn_baixo = keyboard_check(ord("S"))
global.btn_esq = keyboard_check(ord("A"))
global.btn_dir = keyboard_check(ord("D"))
global.btn_tiro = mouse_check_button(mb_left)
